-- AlterTable
ALTER TABLE `Kehadiran` ADD COLUMN `instansi` VARCHAR(191) NULL,
    MODIFY `nim` VARCHAR(191) NULL,
    MODIFY `tipePeserta` ENUM('MAHASISWA', 'PEGAWAI', 'TAMU') NOT NULL DEFAULT 'MAHASISWA';
